import org.teavm.gradle.api.OptimizationLevel

plugins {
  id 'java'
  id("com.github.xpenatan.gdx-teavm") version "1.6.2"
}
eclipse.project.name = appName + "-teavm"

// This must be at least 17, and no higher than the JDK version this project is built with.
java.targetCompatibility = "17"
// This should probably be equal to targetCompatibility, above. This only affects the TeaVM module.
java.sourceCompatibility = "17"

dependencies {
  implementation "com.github.xpenatan.gdx-teavm:backend-web:$gdxTeaVMVersion"
  implementation project(':core')
}

gdxTeaVM {
  assets.from(rootProject.files('assets'))
  webDefaults {
    mainClass.set("com.github.tommyettinger.teavm.TeaVMLauncher")
    htmlTitle.set(appName)
  }

  // Keeps the original development task name.
  js {
    devServer {
      enabled.set(true)
      autoBuild.set(true)
      autoReload.set(true)
      optimization.set(OptimizationLevel.NONE)
    }
  }

  // Independent release variants with isolated output.
  js("release") {
    obfuscated.set(true)
    serverPort.set(8180)
    optimization.set(OptimizationLevel.BALANCED)
  }

  wasm("release") {
    obfuscated.set(true)
    serverPort.set(8181)
    optimization.set(OptimizationLevel.BALANCED)
  }
}

// For backwards compatibility with the earlier run and build tasks.
tasks.register("run"){
  dependsOn("gdx_teavm_web_wasm_release_run")
}
build.dependsOn("gdx_teavm_web_wasm_release_build")
